CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    pass_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS apps (
    id int PRIMARY KEY ,
    name VARCHAR(255) NOT NULL UNIQUE,
    secret_key VARCHAR(255) NOT NULL
);

CREATE OR REPLACE FUNCTION notify_table_update() RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_notify('update_cache', TG_TABLE_NAME);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER secrets_changed
    AFTER INSERT OR UPDATE OR DELETE ON apps
    FOR EACH ROW EXECUTE FUNCTION notify_table_update();