CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    pass_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS apps (
    id int PRIMARY KEY ,
    name VARCHAR(255) NOT NULL UNIQUE,
    secret_key VARCHAR(255) NOT NULL
);